// This file was generated by py/makeversionhdr.py
#define MICROPY_GIT_TAG "4ad81dd-dirty"
#define MICROPY_GIT_HASH "4ad81dd-dirty"
#define MICROPY_BUILD_DATE "2017-07-15"
#define MICROPY_VERSION_MAJOR (0)
#define MICROPY_VERSION_MINOR (0)
#define MICROPY_VERSION_MICRO (1)
#define MICROPY_VERSION_STRING "0.0.1"
